# Generated by Django 4.1.3 on 2022-12-18 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_catgory_post_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catgory',
            new_name='Category',
        ),
    ]
